apiVersion: apps/v1
kind: Deployment
metadata:
  name: Alarm
  labels:
    app: Alarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Alarm
  template:
    metadata:
      labels:
        app: Alarm
    spec:
      containers:
        - name: Alarm
          image: username/Alarm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5